[Default]
hosts = "mysql-master,mysql-slave-1,mysql-slave-2"
user = "root:root"
rpluser = "root:root"
ignore-servers = ""
working-directory = "/var/lib/replication-manager"
share-directory = "/usr/share/replication-manager"
logfile = "/var/log/replication-manager.log"
log-level = 1
multimaster = false
multi-tier-slave = false
maxscale-binlog = false
readonly = true
failover-event-scheduler = false
failover-event-status = false
connect-timeout = 1
force-slave-heartbeat= false
force-slave-heartbeat-retry = 5
force-slave-heartbeat-time = 3
force-slave-gtid-mode = false
force-slave-semisync = false
force-slave-readonly = true
force-binlog-row = false
force-binlog-annotate = false
force-binlog-slowqueries = false
force-inmemory-binlog-cache-size = false
force-disk-relaylog-size-limit = false
force-disk-relaylog-size-limit-size = 1000000000
force-sync-binlog = false
force-sync-innodb = false
force-binlog-checksum = false
http-auth = false
http-bind-address = "0.0.0.0"
http-bootstrap-button = false
http-port = "10001"
http-root = "/usr/share/replication-manager/dashboard"
http-server = true
http-session-lifetime = 3600
pre-failover-script = ""
post-failover-script = ""
interactive = false
monitoring-ticker = 2
check-type = "tcp"
check-replication-filters = true
check-binlog-filters = true
check-replication-state = true
failcount = 2
failcount-reset-time = 300
failover-limit = 9
failover-time-limit = 10
failover-max-slave-delay = 30
failover-falsepositive-heartbeat = true
failover-falsepositive-heartbeat-timeout = 3
failover-falsepositive-maxscale = false
failover-falsepositive-maxscale-timeout = 14
failover-falsepositive-external = false
failover-falsepositive-external-port = 80
arbitration-external = false
switchover-wait-kill = 5000
switchover-wait-trx = 10
switchover-wait-write-query = 10
switchover-max-slave-delay = 30
maxscale = false
maxscale-monitor = false
mariadb-binary-path = "/usr/share/replication-manager"
autorejoin = true
autorejoin-semisync = true
autorejoin-flashback = true
autorejoin-mysqldump = false

